<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="my_suite_1" duration-ms="425" started-at="2020-07-02T21:52:03Z" finished-at="2020-07-02T21:52:03Z">
    <groups>
    </groups>
    <test name="Listener test1" duration-ms="425" started-at="2020-07-02T21:52:03Z" finished-at="2020-07-02T21:52:03Z">
      <class name="com.bwf.ecshop.tests.LoginTest">
        <test-method status="SKIP" signature="testLogin_success(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.bwf.ecshop.tests.LoginTest@26653222]" name="testLogin_success" duration-ms="0" started-at="2020-07-03T05:52:03Z" data-provider="loginTestData" finished-at="2020-07-03T05:52:03Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerExceptionat org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)at org.testng.internal.Parameters.handleParameters(Parameters.java:706)at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:914)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)Caused by: java.lang.NullPointerExceptionat com.bwf.learning.ReadExcel.getDataFromeExcel(ReadExcel.java:47)at com.bwf.ecshop.data.TestDataFactory.getLoginTestData(TestDataFactory.java:17)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)... 22 more]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin_success -->
        <test-method status="PASS" signature="closeService()[pri:0, instance:com.bwf.ecshop.tests.LoginTest@26653222]" name="closeService" is-config="true" duration-ms="1530" started-at="2020-07-03T05:52:04Z" finished-at="2020-07-03T05:52:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeService -->
      </class> <!-- com.bwf.ecshop.tests.LoginTest -->
    </test> <!-- Listener test1 -->
  </suite> <!-- my_suite_1 -->
</testng-results>
